### PR TITLE
Support HTTPS Scheme

### PR DESCRIPTION
**Pull request by zhanang19**
Generate all URL that generated by `URLGenerator` Class will force to use HTTPS Scheme when HTTPS config enabled.

#42

### CODE REVIEW

**Comment by zhanang19** [comment]
#43

**Comment by kossa** [comment]
@zhanang19 It's a force redirection right ?

**Comment by zhanang19** [comment]
No, it only forces URLs generated from assets and route helpers to use the HTTPS scheme

**Comment by kossa** [comment]
I tried this code :
```
Route::get('test', function () {
    return url('/');
});
```

I got: `https://laradminator.local` with HTTPS. so why I have to force https ?

**Pull request closed without merging**
